/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author diego
 */
public class PantallaDell extends javax.swing.JFrame {

    /**
     * Creates new form Pantalla1
     */
    public PantallaDell() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        masEnsamblador = new javax.swing.JButton();
        menosEnsamblador = new javax.swing.JButton();
        masPM = new javax.swing.JButton();
        masCPU = new javax.swing.JButton();
        masRAM = new javax.swing.JButton();
        masFA = new javax.swing.JButton();
        masGPU = new javax.swing.JButton();
        menosPM = new javax.swing.JButton();
        menosCPU = new javax.swing.JButton();
        menosRAM = new javax.swing.JButton();
        menosFA = new javax.swing.JButton();
        menosGPU = new javax.swing.JButton();
        EstadoDirector = new javax.swing.JLabel();
        qtyEnsamblador = new javax.swing.JLabel();
        qtyCPU1 = new javax.swing.JLabel();
        qtyRAM1 = new javax.swing.JLabel();
        qtyFA1 = new javax.swing.JLabel();
        qtyGPU1 = new javax.swing.JLabel();
        qtyPM2 = new javax.swing.JLabel();
        qtyConGPU1 = new javax.swing.JLabel();
        qtyestandar2 = new javax.swing.JLabel();
        qtyDescuentoProjectM = new javax.swing.JLabel();
        qtyAmonestacionesPM2 = new javax.swing.JLabel();
        EstadoProjectManager = new javax.swing.JLabel();
        qtyPMs1 = new javax.swing.JLabel();
        qtyCPUs1 = new javax.swing.JLabel();
        qtyRAMs2 = new javax.swing.JLabel();
        qtyFAs1 = new javax.swing.JLabel();
        qtyGPUs1 = new javax.swing.JLabel();
        qtyDiasRestantes2 = new javax.swing.JLabel();
        qtyGananciasTotales = new javax.swing.JLabel();
        Ingresos = new javax.swing.JLabel();
        Costor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 81, -1, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("DELL");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jButton1.setText("Iniciar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 18)); // NOI18N
        jLabel2.setText("Trabajadores");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 110, 20));

        jLabel3.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 18)); // NOI18N
        jLabel3.setText("Computadoras producidas");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 220, 20));

        jLabel4.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 18)); // NOI18N
        jLabel4.setText("Director");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 70, 20));

        jLabel5.setText("Con GPU: ");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 110, -1));

        jLabel6.setText("Status:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 40, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Placa Madre: ");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, 90, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("CPU: ");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 110, -1));

        jLabel9.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 18)); // NOI18N
        jLabel9.setText("Costos:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 410, 120, 20));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("GPU:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 110, -1));

        jLabel11.setText("Estándar: ");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 110, -1));

        jLabel12.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 18)); // NOI18N
        jLabel12.setText("Project Manager");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 140, 20));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Ensamblador");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        jLabel14.setText("Amonestaciones: ");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 110, -1));

        jLabel15.setText("Descontado: ");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 110, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("RAM: ");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 110, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("Fuente de Alimentación: ");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, 160, -1));

        jLabel18.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 18)); // NOI18N
        jLabel18.setText("Componentes");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 120, 20));

        jLabel19.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 18)); // NOI18N
        jLabel19.setText("Dias Restantes: ");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 310, 180, 20));

        jLabel20.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 18)); // NOI18N
        jLabel20.setText("Ingresos:");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, 120, 20));

        jLabel21.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 18)); // NOI18N
        jLabel21.setText("Ganancias Totales:");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, 180, 20));

        jLabel22.setText("Estatus:");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 40, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel23.setText("Placa Madre");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 80, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel24.setText("CPU");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel25.setText("RAM ");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel26.setText("Fuente Poder");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 90, 20));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel27.setText("GPU");
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, -1, -1));

        masEnsamblador.setText("+");
        masEnsamblador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masEnsambladorActionPerformed(evt);
            }
        });
        jPanel2.add(masEnsamblador, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 30, 30));

        menosEnsamblador.setText("-");
        jPanel2.add(menosEnsamblador, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 30, 30));

        masPM.setText("+");
        masPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masPMActionPerformed(evt);
            }
        });
        jPanel2.add(masPM, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 30, 30));

        masCPU.setText("+");
        masCPU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masCPUActionPerformed(evt);
            }
        });
        jPanel2.add(masCPU, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 30, 30));

        masRAM.setText("+");
        masRAM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masRAMActionPerformed(evt);
            }
        });
        jPanel2.add(masRAM, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 30, 30));

        masFA.setText("+");
        masFA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masFAActionPerformed(evt);
            }
        });
        jPanel2.add(masFA, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 30, 30));

        masGPU.setText("+");
        masGPU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masGPUActionPerformed(evt);
            }
        });
        jPanel2.add(masGPU, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 30, 30));

        menosPM.setText("-");
        jPanel2.add(menosPM, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 30, 30));

        menosCPU.setText("-");
        jPanel2.add(menosCPU, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 30, 30));

        menosRAM.setText("-");
        jPanel2.add(menosRAM, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 30, 30));

        menosFA.setText("-");
        jPanel2.add(menosFA, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 30, 30));

        menosGPU.setText("-");
        jPanel2.add(menosGPU, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 30, 30));

        EstadoDirector.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EstadoDirector.setText("0");
        jPanel2.add(EstadoDirector, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 20, 20));

        qtyEnsamblador.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        qtyEnsamblador.setText("0");
        jPanel2.add(qtyEnsamblador, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, -1, 30));

        qtyCPU1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        qtyCPU1.setText("0");
        jPanel2.add(qtyCPU1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, -1, 30));

        qtyRAM1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        qtyRAM1.setText("0");
        jPanel2.add(qtyRAM1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, -1, 30));

        qtyFA1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        qtyFA1.setText("0");
        jPanel2.add(qtyFA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, -1, 30));

        qtyGPU1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        qtyGPU1.setText("0");
        jPanel2.add(qtyGPU1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, -1, 30));

        qtyPM2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        qtyPM2.setText("0");
        jPanel2.add(qtyPM2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, -1, 30));

        qtyConGPU1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        qtyConGPU1.setText("0");
        jPanel2.add(qtyConGPU1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, 20, 20));

        qtyestandar2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        qtyestandar2.setText("0");
        jPanel2.add(qtyestandar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, -1, -1));

        qtyDescuentoProjectM.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        qtyDescuentoProjectM.setText("0");
        jPanel2.add(qtyDescuentoProjectM, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 20, 20));

        qtyAmonestacionesPM2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        qtyAmonestacionesPM2.setText("0");
        jPanel2.add(qtyAmonestacionesPM2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 20, 20));

        EstadoProjectManager.setText("Viendo Anime");
        jPanel2.add(EstadoProjectManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 100, 20));

        qtyPMs1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        qtyPMs1.setText("0");
        jPanel2.add(qtyPMs1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 80, 20, 20));

        qtyCPUs1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        qtyCPUs1.setText("0");
        jPanel2.add(qtyCPUs1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, 20, 20));

        qtyRAMs2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        qtyRAMs2.setText("0");
        jPanel2.add(qtyRAMs2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, 20, 20));

        qtyFAs1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        qtyFAs1.setText("0");
        jPanel2.add(qtyFAs1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 170, 20, 20));

        qtyGPUs1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        qtyGPUs1.setText("0");
        jPanel2.add(qtyGPUs1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 200, 20, 20));

        qtyDiasRestantes2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        qtyDiasRestantes2.setText("0");
        jPanel2.add(qtyDiasRestantes2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 310, 20, 20));

        qtyGananciasTotales.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        qtyGananciasTotales.setText("0");
        jPanel2.add(qtyGananciasTotales, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 340, 20, 20));

        Ingresos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Ingresos.setText("0");
        jPanel2.add(Ingresos, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, -1, -1));

        Costor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Costor.setText("0");
        jPanel2.add(Costor, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void masEnsambladorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masEnsambladorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_masEnsambladorActionPerformed

    private void masPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masPMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_masPMActionPerformed

    private void masCPUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masCPUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_masCPUActionPerformed

    private void masRAMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masRAMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_masRAMActionPerformed

    private void masFAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masFAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_masFAActionPerformed

    private void masGPUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masGPUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_masGPUActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaDell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaDell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaDell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaDell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaDell().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Costor;
    private javax.swing.JLabel EstadoDirector;
    private javax.swing.JLabel EstadoProjectManager;
    private javax.swing.JLabel Ingresos;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton masCPU;
    private javax.swing.JButton masEnsamblador;
    private javax.swing.JButton masFA;
    private javax.swing.JButton masGPU;
    private javax.swing.JButton masPM;
    private javax.swing.JButton masRAM;
    private javax.swing.JButton menosCPU;
    private javax.swing.JButton menosEnsamblador;
    private javax.swing.JButton menosFA;
    private javax.swing.JButton menosGPU;
    private javax.swing.JButton menosPM;
    private javax.swing.JButton menosRAM;
    private javax.swing.JLabel qtyAmonestacionesPM2;
    private javax.swing.JLabel qtyCPU1;
    private javax.swing.JLabel qtyCPUs1;
    private javax.swing.JLabel qtyConGPU1;
    private javax.swing.JLabel qtyDescuentoProjectM;
    private javax.swing.JLabel qtyDiasRestantes2;
    private javax.swing.JLabel qtyEnsamblador;
    private javax.swing.JLabel qtyFA1;
    private javax.swing.JLabel qtyFAs1;
    private javax.swing.JLabel qtyGPU1;
    private javax.swing.JLabel qtyGPUs1;
    private javax.swing.JLabel qtyGananciasTotales;
    private javax.swing.JLabel qtyPM2;
    private javax.swing.JLabel qtyPMs1;
    private javax.swing.JLabel qtyRAM1;
    private javax.swing.JLabel qtyRAMs2;
    private javax.swing.JLabel qtyestandar2;
    // End of variables declaration//GEN-END:variables
}
