/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import MSIemployees.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.concurrent.Semaphore;

/**
 *
 * @author diego
 */


public class PantallaMSI extends javax.swing.JFrame {

    private int ensambladores = 1;
    private int pm = 1;
    private int cpuWorkers = 1;
    private int ramWorkers = 1;
    private int faWorkers = 1;
    private int gpuWorkers = 1;
    private final int MAX_WORKERS = 16;
    private int totalAssignedWorkers = ensambladores + pm + cpuWorkers + ramWorkers + faWorkers + gpuWorkers;
    
    public PantallaMSI() {
        initComponents();
        actualizarLabels();
    }
    
    public static void guardarParametros(double segundos, int deathline, int n) {
        File file = new File("parametros.txt");

        try {
            // Crear el archivo si no existe
            if (!file.exists()) {
                file.createNewFile();
            }

            // Usar FileWriter para escribir en el archivo
            FileWriter writer = new FileWriter(file, true); // 'true' para agregar sin sobrescribir

            writer.write("Segundos: " + segundos + "\n");
            writer.write("Deathline: " + deathline + "\n");
            writer.write("N: " + n + "\n");
            writer.write("-------------------------\n");

            writer.close();

            System.out.println("Parámetros guardados en parametros.txt");

        } catch (IOException e) {
            System.out.println("Ocurrió un error al guardar los parámetros.");
            e.printStackTrace();
        }
    }
    
    
    private void iniciarSimulacion(int milisegundos, int diastotales, int limite) {
        Semaphore mutex = new Semaphore(1);
        
        Worker trab1 = new MBproducer(mutex, milisegundos, diastotales);
        Worker trab2 = new CPUproducer(mutex, milisegundos, diastotales);
        Worker trab3 = new RAMproducer(mutex, milisegundos, diastotales);
        Worker trab4 = new PSproducer(mutex, milisegundos, diastotales);
        Worker trab5 = new GCproducer(mutex, milisegundos, diastotales);
        Assembler trab6 = new Assembler(mutex, trab1, trab2, trab3, trab4, trab5, milisegundos, diastotales);
        
        ProjectManagerMSI trab7 = new ProjectManagerMSI(mutex, milisegundos, limite, diastotales);
        DirectorMSI trab8 = new DirectorMSI(mutex, milisegundos, trab7, trab6, diastotales);

        // Iniciar los threads
        trab1.start();
        trab2.start();
        trab3.start();
        trab4.start();
        trab5.start();
        trab6.start();
        trab7.start();
        trab8.start();

        try {
            // Esperar que todos los hilos terminen
            trab1.join();
            trab2.join();
            trab3.join();
            trab4.join();
            trab5.join();
            trab6.join();
            trab7.join();
            trab8.join();
        } catch (InterruptedException e) {
            Logger.getLogger(PantallaDell.class.getName()).log(Level.SEVERE, null, e);
        }

        // Calcular la ganancia y mostrar los resultados
        int gananciaBruta = trab8.getVentas();
        int costosOperativos = trab1.getTotalsalary() + trab2.getTotalsalary() + trab3.getTotalsalary() + trab4.getTotalsalary() + trab5.getTotalsalary() + trab6.getTotalsalary() + trab7.getTotalsalary() + trab8.getTotalsalary();
        int UtilidadEstudio = gananciaBruta - costosOperativos;
        bruto.setText(String.valueOf(gananciaBruta)+"$");
        costos.setText(String.valueOf(costosOperativos)+"$");
        ganaciasTotales.setText(String.valueOf(UtilidadEstudio)+"$");
        //javax.swing.JOptionPane.showMessageDialog(this, "Ganancia Bruta: " + gananciaBruta + "\nCostos Operativos: " + costosOperativos + "\nUtilidad del estudio: " + UtilidadEstudio);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel28 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        masEnsamblador = new javax.swing.JButton();
        menosEnsamblador = new javax.swing.JButton();
        masPM = new javax.swing.JButton();
        masCPU = new javax.swing.JButton();
        masRAM = new javax.swing.JButton();
        masFA = new javax.swing.JButton();
        masGPU = new javax.swing.JButton();
        menosPM = new javax.swing.JButton();
        menosCPU = new javax.swing.JButton();
        menosRAM = new javax.swing.JButton();
        menosFA = new javax.swing.JButton();
        menosGPU = new javax.swing.JButton();
        workersMB = new javax.swing.JLabel();
        workerscpu = new javax.swing.JLabel();
        workersram = new javax.swing.JLabel();
        workersPS = new javax.swing.JLabel();
        workersgc = new javax.swing.JLabel();
        costos = new javax.swing.JLabel();
        workersAssembler1 = new javax.swing.JLabel();
        workersAssembler2 = new javax.swing.JLabel();
        bruto = new javax.swing.JLabel();
        ganaciasTotales = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        jLabel28.setBackground(new java.awt.Color(255, 0, 0));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 81, -1, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("MV Boli", 0, 54)); // NOI18N
        jLabel1.setText("MSI");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 80));

        jButton1.setText("Iniciar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 18)); // NOI18N
        jLabel2.setText("Trabajadores");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 110, 20));

        jLabel3.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 18)); // NOI18N
        jLabel3.setText("Computadoras producidas");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 220, 20));

        jLabel4.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 18)); // NOI18N
        jLabel4.setText("Director");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 70, 20));

        jLabel5.setText("Con GPU: ");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 110, -1));

        jLabel6.setText("Status:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 40, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Placa Madre: ");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, 90, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("CPU: ");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 110, -1));

        jLabel9.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 18)); // NOI18N
        jLabel9.setText("Costos:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, 60, 20));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("GPU:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 110, -1));

        jLabel11.setText("Estándar: ");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 110, -1));

        jLabel12.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 18)); // NOI18N
        jLabel12.setText("Project Manager");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 140, 20));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Ensamblador");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        jLabel14.setText("Amonestaciones: ");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 120, -1));

        jLabel15.setText("Descontado: ");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 110, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("RAM: ");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 110, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("Fuente de Alimentación: ");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, 160, -1));

        jLabel18.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 18)); // NOI18N
        jLabel18.setText("Componentes");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 120, 20));

        jLabel19.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 18)); // NOI18N
        jLabel19.setText("Dias Restantes: ");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 310, 130, 20));

        jLabel20.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 18)); // NOI18N
        jLabel20.setText("Ingresos:");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, 70, 20));

        jLabel21.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 18)); // NOI18N
        jLabel21.setText("Ganancias Totales:");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, 150, 20));

        jLabel22.setText("Estatus:");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 60, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel23.setText("Placa Madre");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 80, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel24.setText("CPU");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel25.setText("RAM ");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel26.setText("Fuente Poder");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 90, 20));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel27.setText("GPU");
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, -1));

        masEnsamblador.setText("+");
        masEnsamblador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masEnsambladorActionPerformed(evt);
            }
        });
        jPanel2.add(masEnsamblador, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 50, 30));

        menosEnsamblador.setText("-");
        menosEnsamblador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menosEnsambladorActionPerformed(evt);
            }
        });
        jPanel2.add(menosEnsamblador, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 50, 30));

        masPM.setText("+");
        masPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masPMActionPerformed(evt);
            }
        });
        jPanel2.add(masPM, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 50, 30));

        masCPU.setText("+");
        masCPU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masCPUActionPerformed(evt);
            }
        });
        jPanel2.add(masCPU, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 50, 30));

        masRAM.setText("+");
        masRAM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masRAMActionPerformed(evt);
            }
        });
        jPanel2.add(masRAM, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 50, 30));

        masFA.setText("+");
        masFA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masFAActionPerformed(evt);
            }
        });
        jPanel2.add(masFA, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 50, 30));

        masGPU.setText("+");
        masGPU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masGPUActionPerformed(evt);
            }
        });
        jPanel2.add(masGPU, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 50, 30));

        menosPM.setText("-");
        menosPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menosPMActionPerformed(evt);
            }
        });
        jPanel2.add(menosPM, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 50, 30));

        menosCPU.setText("-");
        menosCPU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menosCPUActionPerformed(evt);
            }
        });
        jPanel2.add(menosCPU, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 50, 30));

        menosRAM.setText("-");
        menosRAM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menosRAMActionPerformed(evt);
            }
        });
        jPanel2.add(menosRAM, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 50, 30));

        menosFA.setText("-");
        menosFA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menosFAActionPerformed(evt);
            }
        });
        jPanel2.add(menosFA, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 50, 30));

        menosGPU.setText("-");
        menosGPU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menosGPUActionPerformed(evt);
            }
        });
        jPanel2.add(menosGPU, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 50, 30));

        workersMB.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        workersMB.setText("0");
        jPanel2.add(workersMB, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, -1, 30));

        workerscpu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        workerscpu.setText("0");
        jPanel2.add(workerscpu, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, -1, 30));

        workersram.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        workersram.setText("0");
        jPanel2.add(workersram, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, -1, 30));

        workersPS.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        workersPS.setText("0");
        jPanel2.add(workersPS, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, -1, 30));

        workersgc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        workersgc.setText("0");
        jPanel2.add(workersgc, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, -1, 30));

        costos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        costos.setText("0");
        jPanel2.add(costos, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, 110, 20));

        workersAssembler1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        workersAssembler1.setText("0");
        jPanel2.add(workersAssembler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, -1, 30));

        workersAssembler2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        workersAssembler2.setText("0");
        jPanel2.add(workersAssembler2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 310, 100, 20));

        bruto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bruto.setText("0");
        jPanel2.add(bruto, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, 110, 20));

        ganaciasTotales.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ganaciasTotales.setText("0");
        jPanel2.add(ganaciasTotales, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 340, 100, 20));

        jPanel3.setBackground(new java.awt.Color(225, 33, 33));
        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 430));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menosGPUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menosGPUActionPerformed
        if (gpuWorkers > 1) {
            gpuWorkers--;
            totalAssignedWorkers--;
            actualizarLabels();
        }
    }//GEN-LAST:event_menosGPUActionPerformed

    private void menosFAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menosFAActionPerformed
        if (faWorkers > 1) {
            faWorkers--;
            totalAssignedWorkers--;
            actualizarLabels();
        }
    }//GEN-LAST:event_menosFAActionPerformed

    private void menosRAMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menosRAMActionPerformed
        if (ramWorkers > 1) {
            ramWorkers--;
            totalAssignedWorkers--;
            actualizarLabels();
        }
    }//GEN-LAST:event_menosRAMActionPerformed

    private void menosCPUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menosCPUActionPerformed
        if (cpuWorkers > 1) {
            cpuWorkers--;
            totalAssignedWorkers--;
            actualizarLabels();
        }
    }//GEN-LAST:event_menosCPUActionPerformed

    private void menosPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menosPMActionPerformed
        if (pm > 1) {
            pm--;
            totalAssignedWorkers--;
            actualizarLabels();
        }
    }//GEN-LAST:event_menosPMActionPerformed

    private void masGPUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masGPUActionPerformed
        if (verificarAsignacion()) {
            gpuWorkers++;
            totalAssignedWorkers++;
            actualizarLabels();
        }
    }//GEN-LAST:event_masGPUActionPerformed

    private void masFAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masFAActionPerformed
        if (verificarAsignacion()) {
            faWorkers++;
            totalAssignedWorkers++;
            actualizarLabels();
        }
    }//GEN-LAST:event_masFAActionPerformed

    private void masRAMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masRAMActionPerformed
        if (verificarAsignacion()) {
            ramWorkers++;
            totalAssignedWorkers++;
            actualizarLabels();
        }
    }//GEN-LAST:event_masRAMActionPerformed

    private void masCPUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masCPUActionPerformed
        if (verificarAsignacion()) {
            cpuWorkers++;
            totalAssignedWorkers++;
            actualizarLabels();
        }
    }//GEN-LAST:event_masCPUActionPerformed

    private void masPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masPMActionPerformed
        if (verificarAsignacion()) {
            pm++;
            totalAssignedWorkers++;
            actualizarLabels();
        }
    }//GEN-LAST:event_masPMActionPerformed

    private void menosEnsambladorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menosEnsambladorActionPerformed
        if (ensambladores > 1) {
            ensambladores--;
            totalAssignedWorkers--;
            actualizarLabels();
        }
    }//GEN-LAST:event_menosEnsambladorActionPerformed

    private void masEnsambladorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masEnsambladorActionPerformed
        if (verificarAsignacion()) {
            ensambladores++;
            totalAssignedWorkers++;
            actualizarLabels();
        }
    }//GEN-LAST:event_masEnsambladorActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {

            if (totalAssignedWorkers == MAX_WORKERS) {
                // Iniciar la simulación
                // Solicitar los milisegundos
                String milisegundosInput = javax.swing.JOptionPane.showInputDialog(this, "Por favor, ingrese un número de milisegundos (1000 milisegundos = 1 segundo):");
                int milisegundos = Integer.parseInt(milisegundosInput);

                // Solicitar el número de días
                String diasInput = javax.swing.JOptionPane.showInputDialog(this, "Por favor, ingrese el número de días:");
                int diastotales = Integer.parseInt(diasInput);

                // Solicitar la DEATHLINE
                String limiteInput = javax.swing.JOptionPane.showInputDialog(this, "Por favor, inserte la DEATHLINE en días:");
                int limite = Integer.parseInt(limiteInput);

                // Iniciar la simulación con los valores capturados
                iniciarSimulacion(milisegundos, diastotales, limite);

                System.out.println("Simulación iniciada con la siguiente asignación:");
                System.out.println("Ensambladores: " + ensambladores);
                System.out.println("Project Managers: " + pm);
                System.out.println("Trabajadores CPU: " + cpuWorkers);
                System.out.println("Trabajadores RAM: " + ramWorkers);
                System.out.println("Trabajadores FA: " + faWorkers);
                System.out.println("Trabajadores GPU: " + gpuWorkers);
            } else {
                System.out.println("Asegúrate de asignar un total de " + MAX_WORKERS + " trabajadores.");
            }
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, ingrese valores válidos.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaMSI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaMSI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaMSI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaMSI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaMSI().setVisible(true);
            }
        });
    }
    
    
    // Función para verificar si se pueden asignar más trabajadores
    private boolean verificarAsignacion() {
        return totalAssignedWorkers < MAX_WORKERS;
    }
    // Acciones para los botones de "+" y "-" de ensambladores

    
    private void actualizarLabels() {
        workersAssembler1.setText(String.valueOf(ensambladores));
        workersMB.setText(String.valueOf(pm));
        workerscpu.setText(String.valueOf(cpuWorkers));
        workersram.setText(String.valueOf(ramWorkers));
        workersPS.setText(String.valueOf(faWorkers));
        workersgc.setText(String.valueOf(gpuWorkers));
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bruto;
    private javax.swing.JLabel costos;
    private javax.swing.JLabel ganaciasTotales;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton masCPU;
    private javax.swing.JButton masEnsamblador;
    private javax.swing.JButton masFA;
    private javax.swing.JButton masGPU;
    private javax.swing.JButton masPM;
    private javax.swing.JButton masRAM;
    private javax.swing.JButton menosCPU;
    private javax.swing.JButton menosEnsamblador;
    private javax.swing.JButton menosFA;
    private javax.swing.JButton menosGPU;
    private javax.swing.JButton menosPM;
    private javax.swing.JButton menosRAM;
    private javax.swing.JLabel workersAssembler1;
    private javax.swing.JLabel workersAssembler2;
    private javax.swing.JLabel workersMB;
    private javax.swing.JLabel workersPS;
    private javax.swing.JLabel workerscpu;
    private javax.swing.JLabel workersgc;
    private javax.swing.JLabel workersram;
    // End of variables declaration//GEN-END:variables
    
    
        
    
    }

